name: Feature Request
description: Suggest a new feature
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What feature do you want?
    validations:
      required: true
  - type: textarea
    id: usecase
    attributes:
      label: Use case
      description: Why do you need this? What problem does it solve?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workarounds or alternative solutions?
